import asyncio
import os
import time
import uuid
from pathlib import Path
from typing import Any, Optional

from fastapi import FastAPI, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from device_edge.control_protocol import build_be_r, build_fe_w, normalize_command, protocol_time
from .shared_memory_store import SharedMemoryNotReady, attach_existing, inspect_memory, read_snapshot
from .snapshot_normalizer import normalize_snapshot


app = FastAPI(title="Shared Memory Router Test")

ROOT_DIR = Path(__file__).resolve().parents[1]
WEB_INDEX = ROOT_DIR / "web" / "edge-ingest-dashboard.html"
WEB_MEMORY = ROOT_DIR / "web" / "memory-dashboard.html"
WEB_DEBUG = ROOT_DIR / "web" / "memory-debug.html"
uploaded_edge_snapshots: dict[str, dict[str, Any]] = {}
pending_edge_commands: dict[str, list[dict[str, Any]]] = {}
command_results: dict[str, dict[str, Any]] = {}
command_records: dict[str, dict[str, Any]] = {}
command_status_events: dict[str, dict[str, Any]] = {}
command_status_event_order: list[str] = []
command_status_websockets: set[WebSocket] = set()
# Gateway heartbeat and device telemetry age are evaluated independently.
# Keep the old environment key as a compatible override for existing setups.
EDGE_GATEWAY_TTL_SECONDS = max(float(os.getenv("EDGE_GATEWAY_TTL_SECONDS", os.getenv("EDGE_SNAPSHOT_TTL_SECONDS", "20"))), 1.0)
DEVICE_DATA_STALE_SECONDS = max(float(os.getenv("DEVICE_DATA_STALE_SECONDS", "15")), 1.0)


class EdgeSnapshotUpload(BaseModel):
    edge_id: str = Field(..., description="Unique industrial PC or edge agent id")
    device_ip: str = Field(default="", description="Configured IP address of the industrial PC")
    agent_version: str = "dev"
    uploaded_at: float = Field(..., description="Unix timestamp generated by the edge uploader")
    snapshot: dict[str, Any]


class StopCommandRequest(BaseModel):
    operator_id: str = "web-admin"
    reason: str = "manual stop from Vue dashboard"


class HoldCommandRequest(BaseModel):
    operator_id: str = "web-admin"
    reason: str = "manual hold from Vue dashboard"


class SkipStepCommandRequest(BaseModel):
    operator_id: str = "web-admin"
    reason: str = "manual step skip from Vue dashboard"


class StartCommandRequest(BaseModel):
    operator_id: str = "web-admin"
    reason: str = "manual start from Vue dashboard"
    target_temperature: float = 25.0
    target_humidity: float = 60.0


class CommandResultUpload(BaseModel):
    event_id: str = ""
    edge_id: str = ""
    command_id: str = ""
    device_id: str = ""
    status: str = "EXECUTED"
    message: str = ""
    reported_at: float = Field(default_factory=time.time)
    payload: dict[str, Any] = Field(default_factory=dict)
    successMessage: str = ""
    time: str = ""


class ControllerCommandRequest(BaseModel):
    command: str
    time: Optional[str] = None
    operator_id: str = "web-admin"
    reason: str = "command from Vue dashboard"
    payload: dict[str, Any] = Field(default_factory=dict)


def get_snapshot() -> dict[str, Any]:
    shm = attach_existing()
    try:
        snapshot = normalize_snapshot(read_snapshot(shm))
    finally:
        shm.close()
    # Local shared-memory mode is still a gateway: its heartbeat is the latest
    # successful writer update, while the device telemetry is evaluated below.
    now = time.time()
    for device in snapshot.get("devices", []):
        if not isinstance(device, dict):
            continue
        device["gateway_online"] = True
        device["gateway_last_seen_at"] = snapshot.get("written_at")
        _apply_device_health(device, snapshot, now)
    return snapshot


def get_uploaded_snapshot() -> dict[str, Any]:
    edges = list(uploaded_edge_snapshots.values())
    if not edges:
        raise SharedMemoryNotReady("No uploaded edge snapshots yet.")

    devices: list[dict[str, Any]] = []
    latest_written_at = 0.0
    latest_sequence = 0
    now = time.time()
    for edge in edges:
        snapshot = edge.get("snapshot", {})
        stale_seconds = edge_stale_seconds(edge, now)
        is_stale = stale_seconds >= EDGE_GATEWAY_TTL_SECONDS
        latest_written_at = max(latest_written_at, float(snapshot.get("written_at") or edge.get("received_at") or 0))
        try:
            latest_sequence = max(latest_sequence, int(snapshot.get("sequence") or 0))
        except (TypeError, ValueError):
            pass
        for device in snapshot.get("devices", []):
            merged = dict(device)
            merged.setdefault("edge_id", edge.get("edge_id"))
            merged.setdefault("edge_ip", edge.get("edge_ip"))
            configured_ip = (
                merged.get("device_ip")
                or merged.get("ip_address")
                or merged.get("ip")
                or edge.get("device_ip")
                or edge.get("edge_ip")
            )
            merged.setdefault("device_ip", configured_ip)
            merged.setdefault("ip_address", configured_ip)
            merged.setdefault("ip", configured_ip)
            merged.setdefault("edge_received_at", edge.get("received_at"))
            merged["gateway_online"] = not is_stale
            merged["gateway_last_seen_at"] = edge.get("received_at")
            merged["edge_stale"] = is_stale
            merged["stale_seconds"] = round(stale_seconds, 1)
            if is_stale:
                merged.update({
                    "online": False,
                    "device_online": False,
                    "communication_state": "GATEWAY_OFFLINE",
                    "data_quality": "UNKNOWN",
                    "run_state": "OFFLINE",
                    "status_text": "网关心跳超时",
                    "alarm": None,
                    "alarms": [],
                })
            else:
                _apply_device_health(merged, snapshot, now)
            devices.append(merged)

    return {
        "source": "edge_ingest",
        "sequence": latest_sequence,
        "written_at": latest_written_at or time.time(),
        "edge_count": len(edges),
        "stale_edge_count": sum(
            edge_stale_seconds(edge, now) >= EDGE_GATEWAY_TTL_SECONDS for edge in edges
        ),
        "devices": devices,
    }


def get_realtime_snapshot() -> dict[str, Any]:
    if uploaded_edge_snapshots:
        return get_uploaded_snapshot()
    return get_snapshot()


def find_edge_id_for_device(device_id: str) -> Optional[str]:
    for edge_id, edge in uploaded_edge_snapshots.items():
        if edge_stale_seconds(edge) >= EDGE_GATEWAY_TTL_SECONDS:
            continue
        devices = edge.get("snapshot", {}).get("devices", [])
        if any(device.get("device_id") == device_id for device in devices):
            return edge_id
    return None


def edge_stale_seconds(edge: dict[str, Any], now: Optional[float] = None) -> float:
    """Return how long an edge has been silent since its last accepted upload."""
    received_at = edge.get("received_at")
    try:
        return max(0.0, (now or time.time()) - float(received_at))
    except (TypeError, ValueError):
        return float("inf")


def _apply_device_health(device: dict[str, Any], snapshot: dict[str, Any], now: float) -> None:
    """Attach production health semantics while preserving the legacy online key."""
    device_online = bool(device.get("device_online", device.get("online", True)))
    data_updated_at = _as_timestamp(
        device.get("data_updated_at") or device.get("device_last_success_at")
        or device.get("updated_at") or snapshot.get("written_at")
    )
    data_age_seconds = max(0.0, now - data_updated_at) if data_updated_at else float("inf")
    data_stale = data_age_seconds >= DEVICE_DATA_STALE_SECONDS

    device["device_online"] = device_online
    device["device_last_success_at"] = device.get("device_last_success_at") or (data_updated_at if device_online else None)
    device["data_updated_at"] = data_updated_at or None
    device["data_age_seconds"] = round(data_age_seconds, 1) if data_updated_at else None
    device["data_quality"] = "STALE" if device_online and data_stale else ("FRESH" if device_online else "UNKNOWN")
    device["communication_state"] = "DEVICE_OFFLINE" if not device_online else ("DATA_STALE" if data_stale else "ONLINE")
    # Compatibility: old clients still receive a boolean reflecting fresh,
    # device-level communications.
    device["online"] = device_online and not data_stale
    if not device_online:
        device["run_state"] = "OFFLINE"
        device.setdefault("communication_error", device.get("status_text") or "控制器通讯故障")


def _as_timestamp(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def queue_edge_command(edge_id: str, command: dict[str, Any]) -> None:
    pending_edge_commands.setdefault(edge_id, []).append(command)
    command_records[command["command_id"]] = command


def _command_metadata(command: dict[str, Any]) -> dict[str, Any]:
    """Return the FE_W payload plus the server-side correlation metadata."""
    return {
        "command_id": command["command_id"],
        "device_id": command["device_id"],
        "edge_id": command["edge_id"],
        "command_type": command["command_type"],
        **command["fe_w"],
    }


def _remember_command_status_event(event_id: str, event: dict[str, Any]) -> None:
    command_status_events[event_id] = event
    command_status_event_order.append(event_id)
    while len(command_status_event_order) > 20:
        command_status_events.pop(command_status_event_order.pop(0), None)


async def _broadcast_command_status(event: dict[str, Any]) -> None:
    message = {"type": "command_status", **event}
    disconnected: list[WebSocket] = []
    for websocket in tuple(command_status_websockets):
        try:
            await websocket.send_json(message)
        except Exception:
            disconnected.append(websocket)
    for websocket in disconnected:
        command_status_websockets.discard(websocket)


def make_edge_command(
    device_id: str,
    command: str,
    *,
    operator_id: str = "web-admin",
    reason: str = "command from Vue dashboard",
    payload: Optional[dict[str, Any]] = None,
    when: Optional[str] = None,
) -> dict[str, Any]:
    edge_id = find_edge_id_for_device(device_id)
    if not edge_id:
        raise HTTPException(status_code=404, detail=f"No uploaded edge found for device: {device_id}")
    try:
        fe_w = build_fe_w(command, when)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    _, command_type = normalize_command(command)
    item = {
        "command_id": f"CMD-{uuid.uuid4().hex[:10].upper()}",
        "device_id": device_id,
        "edge_id": edge_id,
        "command_type": command_type,
        "operator_id": operator_id,
        "reason": reason,
        "created_at": time.time(),
        "status": "PENDING",
        "payload": payload or {},
        "fe_w": fe_w,
    }
    queue_edge_command(edge_id, item)
    return item


@app.get("/")
async def index() -> FileResponse:
    return FileResponse(WEB_INDEX)


@app.get("/memory")
async def memory_page() -> FileResponse:
    return FileResponse(WEB_MEMORY)


@app.get("/debug")
async def debug_page() -> FileResponse:
    return FileResponse(WEB_DEBUG)


@app.get("/api/memory/snapshot")
async def memory_snapshot() -> dict[str, Any]:
    try:
        return get_realtime_snapshot()
    except SharedMemoryNotReady as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@app.get("/api/memory/devices")
async def memory_devices() -> list[dict[str, Any]]:
    snapshot = await memory_snapshot()
    return snapshot["devices"]


@app.post("/api/device-ingest/snapshots")
async def upload_edge_snapshot(upload: EdgeSnapshotUpload, request: Request) -> dict[str, Any]:
    source_ip = request.client.host if request.client else None
    device_ip = upload.device_ip.strip() or source_ip
    normalized_snapshot = normalize_snapshot(upload.snapshot)
    uploaded_edge_snapshots[upload.edge_id] = {
        "edge_id": upload.edge_id,
        "edge_ip": device_ip,
        "device_ip": device_ip,
        "source_ip": source_ip,
        "agent_version": upload.agent_version,
        "uploaded_at": upload.uploaded_at,
        "received_at": time.time(),
        "snapshot": normalized_snapshot,
        "raw_snapshot": upload.snapshot,
    }
    return {
        "status": "accepted",
        "edge_id": upload.edge_id,
        "edge_ip": device_ip,
        "device_ip": device_ip,
        "source_ip": source_ip,
        "received_at": uploaded_edge_snapshots[upload.edge_id]["received_at"],
        "device_count": len(normalized_snapshot.get("devices", [])),
        "sequence": normalized_snapshot.get("sequence"),
    }


@app.get("/api/device-ingest/latest")
async def latest_uploaded_snapshots() -> dict[str, Any]:
    return {
        "edge_count": len(uploaded_edge_snapshots),
        "edges": uploaded_edge_snapshots,
    }


@app.post("/api/devices/{device_id}/commands")
async def controller_command(device_id: str, request: ControllerCommandRequest) -> dict[str, Any]:
    item = make_edge_command(
        device_id,
        request.command,
        operator_id=request.operator_id,
        reason=request.reason,
        payload=request.payload,
        when=request.time,
    )
    return {
        "status": "QUEUED",
        "command_id": item["command_id"],
        "device_id": device_id,
        "edge_id": item["edge_id"],
        "command": item["fe_w"]["command"],
        "time": item["fe_w"]["time"],
    }


@app.post("/api/devices/{device_id}/stop-requests")
async def stop_device(device_id: str, request: StopCommandRequest) -> dict[str, Any]:
    edge_id = find_edge_id_for_device(device_id)
    if not edge_id:
        raise HTTPException(status_code=404, detail=f"No uploaded edge found for device: {device_id}")

    command = {
        "command_id": f"CMD-{uuid.uuid4().hex[:10].upper()}",
        "device_id": device_id,
        "edge_id": edge_id,
        "command_type": "STOP_TEST",
        "operator_id": request.operator_id,
        "reason": request.reason,
        "created_at": time.time(),
        "status": "PENDING",
        "payload": {
            "reason": request.reason,
        },
        "fe_w": build_fe_w("Stop"),
    }
    queue_edge_command(edge_id, command)
    return {
        "status": "QUEUED",
        "edge_id": edge_id,
        "device_id": device_id,
        "command_id": command["command_id"],
        "command_type": command["command_type"],
    }


@app.post("/api/devices/{device_id}/start-requests")
async def start_device(device_id: str, request: StartCommandRequest) -> dict[str, Any]:
    edge_id = find_edge_id_for_device(device_id)
    if not edge_id:
        raise HTTPException(status_code=404, detail=f"No uploaded edge found for device: {device_id}")

    command = {
        "command_id": f"CMD-{uuid.uuid4().hex[:10].upper()}",
        "device_id": device_id,
        "edge_id": edge_id,
        "command_type": "START_TEST",
        "operator_id": request.operator_id,
        "reason": request.reason,
        "created_at": time.time(),
        "status": "PENDING",
        "payload": {
            "target_temperature": request.target_temperature,
            "target_humidity": request.target_humidity,
            "reason": request.reason,
        },
        "fe_w": build_fe_w("Run"),
    }
    queue_edge_command(edge_id, command)
    return {
        "status": "QUEUED",
        "edge_id": edge_id,
        "device_id": device_id,
        "command_id": command["command_id"],
        "command_type": command["command_type"],
    }


@app.post("/api/devices/{device_id}/hold-requests")
async def hold_device(device_id: str, request: HoldCommandRequest) -> dict[str, Any]:
    edge_id = find_edge_id_for_device(device_id)
    if not edge_id:
        raise HTTPException(status_code=404, detail=f"No uploaded edge found for device: {device_id}")

    command = {
        "command_id": f"CMD-{uuid.uuid4().hex[:10].upper()}",
        "device_id": device_id,
        "edge_id": edge_id,
        "command_type": "HOLD_TEST",
        "operator_id": request.operator_id,
        "reason": request.reason,
        "created_at": time.time(),
        "status": "PENDING",
        "payload": {
            "reason": request.reason,
        },
        "fe_w": build_fe_w("Hold"),
    }
    queue_edge_command(edge_id, command)
    return {
        "status": "QUEUED",
        "edge_id": edge_id,
        "device_id": device_id,
        "command_id": command["command_id"],
        "command_type": command["command_type"],
    }


@app.post("/api/devices/{device_id}/skip-step-requests")
async def skip_step_device(device_id: str, request: SkipStepCommandRequest) -> dict[str, Any]:
    edge_id = find_edge_id_for_device(device_id)
    if not edge_id:
        raise HTTPException(status_code=404, detail=f"No uploaded edge found for device: {device_id}")

    command = {
        "command_id": f"CMD-{uuid.uuid4().hex[:10].upper()}",
        "device_id": device_id,
        "edge_id": edge_id,
        "command_type": "SKIP_STEP",
        "operator_id": request.operator_id,
        "reason": request.reason,
        "created_at": time.time(),
        "status": "PENDING",
        "payload": {
            "reason": request.reason,
        },
        "fe_w": build_fe_w("Jnmp"),
    }
    queue_edge_command(edge_id, command)
    return {
        "status": "QUEUED",
        "edge_id": edge_id,
        "device_id": device_id,
        "command_id": command["command_id"],
        "command_type": command["command_type"],
    }


@app.get("/api/device-commands/pending")
async def pending_commands(edge_id: str) -> dict[str, Any]:
    commands = pending_edge_commands.pop(edge_id, [])
    for command in commands:
        command["status"] = "DELIVERED"
        command["delivered_at"] = time.time()
        command_records[command["command_id"]].update({"status": "DELIVERED", "delivered_at": command["delivered_at"]})
    return {
        "edge_id": edge_id,
        "commands": commands,
    }


@app.get("/api/device-commands/fe-w")
async def fe_w_commands(edge_id: str) -> dict[str, Any]:
    """Expose FE_W plus correlation metadata required for execution status."""
    commands = pending_edge_commands.pop(edge_id, [])
    for command in commands:
        command["status"] = "DELIVERED"
        command["delivered_at"] = time.time()
        command_records[command["command_id"]].update({"status": "DELIVERED", "delivered_at": command["delivered_at"]})
    return {"edge_id": edge_id, "commands": [_command_metadata(command) for command in commands]}


@app.post("/api/device-commands/results")
async def upload_command_result(result: CommandResultUpload) -> dict[str, Any]:
    event_id = result.event_id or f"LEGACY-{uuid.uuid4().hex[:10].upper()}"
    if event_id in command_status_events:
        existing = command_status_events[event_id]
        return {
            "status": "duplicate",
            "event_id": event_id,
            "command_id": existing.get("command_id", result.command_id),
            "duplicate": True,
            "received_at": existing.get("received_at"),
        }
    success_message = result.successMessage or result.message
    result_time = result.time or protocol_time()
    received_at = time.time()
    status_event = {
        "event_id": event_id,
        "edge_id": result.edge_id,
        "command_id": result.command_id,
        "device_id": result.device_id,
        "status": result.status,
        "message": result.message,
        "reported_at": result.reported_at,
        "payload": result.payload,
        "successMessage": success_message,
        "time": result_time,
        "received_at": received_at,
    }
    _remember_command_status_event(event_id, status_event)
    result_key = result.command_id or event_id
    command_results[result_key] = {
        **status_event,
        "be_r": {"successMessage": success_message, "time": result_time},
    }
    command_record = command_records.get(result.command_id)
    if command_record is not None:
        command_record.update({"status": result.status, "result": status_event})
    await _broadcast_command_status(status_event)
    return {
        "status": "accepted",
        "event_id": event_id,
        "command_id": result.command_id,
        "received_at": received_at,
    }


@app.post("/api/device-commands/be-r")
async def receive_be_r(result: dict[str, Any], edge_id: str = "") -> dict[str, Any]:
    """Receive the exact BE_R payload returned by a device controller."""
    success_message = str(result.get("successMessage", "")).strip()
    if not success_message:
        raise HTTPException(status_code=400, detail="BE_R requires successMessage")
    wire = build_be_r(success_message, str(result.get("time") or protocol_time()))
    result_id = f"BE-R-{uuid.uuid4().hex[:10].upper()}"
    command_results[result_id] = {
        "edge_id": edge_id,
        "command_id": result_id,
        "status": "EXECUTED",
        "message": success_message,
        "reported_at": time.time(),
        "payload": {},
        "be_r": wire,
        "received_at": time.time(),
    }
    return wire


@app.get("/api/device-commands/results")
async def latest_command_results() -> dict[str, Any]:
    return {
        "result_count": len(command_results),
        "results": command_results,
        "events": command_status_events,
    }


@app.get("/api/memory/debug")
async def memory_debug() -> dict[str, Any]:
    try:
        shm = attach_existing()
        try:
            info = inspect_memory(shm)
            snapshot = normalize_snapshot(read_snapshot(shm))
        finally:
            shm.close()
    except SharedMemoryNotReady as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    devices = snapshot.get("devices", [])
    return {
        "memory": info,
        "snapshot_summary": {
            "source": snapshot.get("source"),
            "sequence": snapshot.get("sequence"),
            "written_at": snapshot.get("written_at"),
            "device_count": len(devices),
            "device_ids": [device.get("device_id") for device in devices],
            "fields_per_device": sorted(devices[0].keys()) if devices else [],
        },
        "snapshot": snapshot,
    }


@app.websocket("/ws/memory")
async def memory_websocket(websocket: WebSocket) -> None:
    await websocket.accept()
    command_status_websockets.add(websocket)
    try:
        while True:
            try:
                snapshot = get_realtime_snapshot()
                await websocket.send_json({
                    "type": "memory_snapshot",
                    "router_read_at": time.time(),
                    "snapshot": snapshot,
                })
            except SharedMemoryNotReady as exc:
                await websocket.send_json({
                    "type": "memory_not_ready",
                    "message": str(exc),
                    "router_read_at": time.time(),
                })
            await asyncio.sleep(0.25)
    except WebSocketDisconnect:
        pass
    finally:
        command_status_websockets.discard(websocket)
